version: "3.9"
services:
  db-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - estate-backend-db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  api:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Node.js application's Dockerfile
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # Add any other environment variables needed for your email service
    depends_on:
      - db-postgres
      - redis
    ports:
      - '3000:3000'